### ISSUE TITLE
Out-of-Stock Threshold can not be negative in combination with backorders

### ISSUE THREAD

**Issue by paales** [magento/inventory#1370]
### Preconditions
1. Fairly recent branch

### Steps to reproduce
1. Set backorders to 'allow qty below 0'
2. Set 'Out-of-Stock Threshold' to a negative number
3. Save product

### Expected result

1. Qty becomes negative and allows you to purchase the product until the negative qty is reached.

### Actual result
1. Qty stays zero

**Comment by maghamed** [comment]
@paales this looks like an existing behavior of Magento 

https://github.com/magento/magento2/blob/9c14af7a97bcf338662de365d2613c7ca9dbf8c6/app/code/Magento/Catalog/Controller/Adminhtml/Product/Initialization/StockDataFilter.php#L63-L65
```
\Magento\Catalog\Controller\Adminhtml\Product\Initialization\StockDataFilter

        if (isset($stockData['min_qty']) && (int)$stockData['min_qty'] < 0) {
            $stockData['min_qty'] = 0;
        }
```

This  code exists since 24/01/2014 

But I agree that it should be something like 

```
        if (isset($stockData['min_qty']) && (int)$stockData['min_qty'] < 0) {
            if (isset($stockData['backorders']) && (int)$stockData['backorders'] === 0) {
                $stockData['min_qty'] = 0;
            }
        }
```

To support negative Min Threshold if Backorder enabled.

But at this moment we can't just apply this small fix as this will break all the mathematics we have both in MSI as well as in Legacy Inventory, as our existing calculations looks like:

```
\Magento\InventorySales\Model\IsProductSalableForRequestedQtyCondition\
IsSalableWithReservationsCondition::execute
{
        //...
        $qtyWithReservation = $stockItemData[GetStockItemDataInterface::QUANTITY] +
            $this->getReservationsQuantity->execute($sku, $stockId);
        /** @var StockItemConfigurationInterface $stockItemConfiguration */
        $stockItemConfiguration = $this->getStockItemConfiguration->execute($sku, $stockId);
        $qtyLeftInStock = $qtyWithReservation - $stockItemConfiguration->getMinQty() - $requestedQty;
}
```

Thus, now we have equation `$qtyLeftInStock = $qtyWithReservation - $stockItemConfiguration->getMinQty() - $requestedQty;`

**Comment by maghamed** [comment]
need to allow negative  'Out-of-Stock Threshold' just in case Backorder are enabled

In opposite case - preserve existing behaviour (set Out-of-Stock Threshold to 0)

**Comment by orlangur** [comment]
@aleron75 working on this in scope of #kiev-cd

**Comment by aleron75** [comment]
Hi @maghamed, digging into the code I think that the following code from `\Magento\Catalog\Controller\Adminhtml\Product\Initialization\StockDataFilter::filter()`

```
    public function filter(array $stockData)
    {
        ...
        if (isset($stockData['min_qty']) && (int)$stockData['min_qty'] < 0) {
            $stockData['min_qty'] = 0;
        }
        ...
        return $stockData;
    }
```
should take into consideration whether backorders are enabled in current product stock **or in stock configuration**; thus my proposal is:

```
    public function filter(array $stockData)
    {
        ...
        if (isset($stockData['min_qty']) && (int)$stockData['min_qty'] < 0) {
            if ((isset($stockData['backorders']) && (int)$stockData['backorders'] === 0)
                || (isset($stockData['use_config_backorders']) 
                    && (int)$stockData['use_config_backorders'] === 1
                    && $this->stockConfiguration->getBackorders()) === 0) {
                $stockData['min_qty'] = 0;
            }
        }
        ...
        return $stockData;
    }
```

Another point I think I should change is in the `\Magento\CatalogInventory\Model\System\Config\Backend\Minqty::beforeSave()`:

```
    public function beforeSave()
    {
        parent::beforeSave();
        $minQty = (int) $this->getValue() >= 0 ? (int) $this->getValue() : (int) $this->getOldValue();
        $this->setValue((string) $minQty);
        return $this;
    }
```

Also, in this case, I would force positive values only if backorders are not allowed.

What do you think?

**Comment by aleron75** [comment]
After reasoning with @paales, here is the summary of possible config values:
- with **backorders enabled**, only **< 0** values are meaningful for **out-of-stock threshold**
- with **backorders disabled**, only **>= 0** values are meaningful for **out-of-stock threshold**

**Comment by aleron75** [comment]
Hi @lorikrell this is more or less the comment I would add to the out-of-stock threshold field:

> If backorders are allowed, specify only negative values. If backorders are not allowed, specify only values equal to or greater than zero.

Here is a link to a screenshot: https://www.dropbox.com/s/8zdi98setx6fka3/20180703-min-qty-comment.png?dl=0

I'm not native English speaker so maybe there is a better way to express the concept.

Thank you

**Comment by maghamed** [comment]
From @mbrinton01 

```
this should be handled by logic, and not overwriting what is in the fields
For example, if you have backorders enabled and a negative qty in the field
and then disable backorders
we should consider the qty to be zero
but we should not overwrite it. In this same example, if you then enable backorders again
the same negative qty from step 1 should still be there, and be used
```

So that we should add some description to the Advanced Inventory page describing how the logic works, i.e.
```
with backorders enabled, only < 0 values are meaningful for out-of-stock threshold
with backorders enabled,  0 value considered as an infinite out-of-stock threshold
with backorders disabled, only > 0 values are meaningful for out-of-stock threshold
```

**Comment by gitfredrik** [comment]
I have a client that would also benefit from functionality like this.
He offers "pre-order" on new products that are not yet in stock. So we allow backorders. He knows the shipment will be for 100 items so -100 in out of stock threshold would mean he wouldn´t sell more thru pre-order than he knows he´s gonna get in stock.

**Comment by frostbitten** [comment]
Was this issue fixed? I have backorders enabled (by "Allow Qty Below 0") and I'm not able to set my Out of Stock Threshold to below zero on the product page nor the configuration page. I can import a CSV file where the out_of_stock_qty field is negative just fine but if I were to edit the product in the backend after that it would reset it back to 0. It seems I'm only able to backorder items where the stock status is "In Stock" and the amount of stock is greater than the "out of stock threshold." Does this seem like the correct functionality?

**Comment by mbrinton01** [comment]
This has been fixed following the release of MSI (Multi-Source Inventory). You can set the Out-of-Stock threshold to a negative number. Magento will persist this value (instead of resetting to 0 as you describe above) and allow backorders only to this amount.

For example, if the product qty is 100 and the Out-of-Stock Threshold is -70, then orders can be placed up to 170 items, but not beyond that amount.

**Comment by GaryVM** [comment]
Running 2.3.3 and using MSI. The setting to Out-Of-Stock Threshold can now be changed to a negative number in the settings as a default but does appear to still revert to 0 after save if changed on an individual product on the Advanced Inventory. 

Even with a negative OOS threshold and allowing backorders the system still will not allow a shipment to be made for a zero qty product - Not all of your products are available in the requested quantity.

Orders can be made and invoiced but not shipped.

**Comment by mbrinton01** [comment]
I can't replicate the revert to 0 behavior you describe. If I set the Out-Of-Stock Threshold for a single product under Advanced Inventory to a negative number, this value will be saved and remain after exiting the product page.

The system should not allow a shipment for a zero qty product and this is working as designed. This is because the product is backordered - there is not enough physical quantity to make a shipment.

**Comment by krearthur** [comment]
I'm running magento 2.3.6 and can confirm the same behaviour, after saving a product the out-of-stock-threshold (min_qty in code) reverts back to 0. I don't understand why this issue is closed, when it clearly isn't fixed.
