### ISSUE TITLE
InventorySourceSelection Address model expects postalcode to be string while it can be NULL

### ISSUE THREAD

**Issue by dverkade** [magento/inventory#2362]
### Description
The class InventorySourceSelection/Model/Address expects postalcode to be string while it can be NULL. This happens for countries where postalcode is not a required field in Magento and the customer doesn't fill in the postalcode field in the checkout. 

### Preconditions 
1. Magento 2.3.1

### Steps to reproduce
1. Create an order on the frontend where shipping destination is Ireland.
2. Fill in the required fields in the checkout. Zip / Postalcode is not required and should be left empty.
3. Place the order
4. Go into the backoffice and create the invoice for the created order. 

### Expected result
1. Invoice can be created, no error message is shown

### Actual result
1. Invoice can't be created, shows error message on frontend. 
2. In the log files the following error message can be found: 
```
main.CRITICAL: Type Error occurred when creating object: Magento\InventorySourceSelection\Model\Address, Argument 2 passed to Magento\InventorySourceSelection\Model\Address::__construct() must be of the type string, null given, called in /home/elektor/domains/elektor.com/public_html/releases/20190624074455/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 116 [] []
```

**Comment by smoskaluk** [comment]
Hi @dverkade thank you for your report! I've got the same error like you describe, but after creating Shipment, not Invoice. May you, please, recheck the issue and update description?

**Comment by smoskaluk** [comment]
fixed in 2.3-develop

**Comment by ishakhsuvarov** [comment]
Contents of 2.3-develop would be released as Inventory 1.1.4 (Magento 2.3.4)

**Comment by mamsincl** [comment]
Hi @magento-team 

I know it is closed, but experiencing almost the same issue with 2.3.5

```
 [2020-06-18 09:54:35] main.CRITICAL: Type Error occurred when creating object: 
Magento\InventorySourceSelection\Model\Address, Argument 5 passed to 
Magento\InventorySourceSelection\Model\Address::__construct() must be of 
the type string, null given, called in 
/var/www/xxxxxxxxxxxxxxxxxxxxxx/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php 
on line 121 [] []
```
the order placed without any address data, according to class constructor only having issue with city

**Comment by pmonosolo** [comment]
I'm experiencing the same on 2.4.3. This seems to be due to some inventory issue where one item is missing from the cart due to stock and another item in the cart. 

1) Client goes to shop, puts item into cart
2) At night the item goes out of stock
3) Client comes back, puts a different item into cart
4) Client visits Cart or Checkout page - error shows up on both.

**Comment by pmonosolo** [comment]
The weird part is that the displaying errors is TURNED OFF everywhere, but the error still shows up uncovering server path!

**Comment by gmalhotra02** [comment]
I am facing the same error in Magento 2.4.3 any solution?

error is : Type Error occurred when creating object: Magento\InventorySourceSelection\Model\Address, Argument 1 passed to Magento\InventorySourceSelection\Model\Address::__construct() must be of the type string, null given, called in /var/www/public_html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121

**Comment by pmonosolo** [comment]
> I am facing the same error in Magento 2.4.3 any solution?
> 
> error is : Type Error occurred when creating object: Magento\InventorySourceSelection\Model\Address, Argument 1 passed to Magento\InventorySourceSelection\Model\Address::__construct() must be of the type string, null given, called in /var/www/public_html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121

Are you using Amasty Shipping Table rates?

**Comment by gmalhotra02** [comment]
> > I am facing the same error in Magento 2.4.3 any solution?
> 
> > 
> 
> > error is : Type Error occurred when creating object: Magento\InventorySourceSelection\Model\Address, Argument 1 passed to Magento\InventorySourceSelection\Model\Address::__construct() must be of the type string, null given, called in /var/www/public_html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121
> 
> 
> 
> Are you using Amasty Shipping Table rates? 

Yes, I am using Amasty Shipping Table rate extension. Any changes to be done to the module ?

**Comment by pmonosolo** [comment]
> > > I am facing the same error in Magento 2.4.3 any solution?
> > 
> > 
> > > 
> > 
> > 
> > > error is : Type Error occurred when creating object: Magento\InventorySourceSelection\Model\Address, Argument 1 passed to Magento\InventorySourceSelection\Model\Address::__construct() must be of the type string, null given, called in /var/www/public_html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121
> > 
> > 
> > Are you using Amasty Shipping Table rates?
> 
> Yes, I am using Amasty Shipping Table rate extension. Any changes to be done to the module ?

Go to:
/Model/Quote/Inventory/InventoryRequestFromQuoteFactory.php

and change:

```
-            'country'   => $shippingAddress->getCountryId(),
+            'country'   => $shippingAddress->getCountryId() ?? '',
```

This fixed the issue for me.

To test you can:

Use guest account, add to cart, then go straight to login page and log in. This should show the error on cart / checkout pages. 

I requested Amasty team expedite this fix, but I don't know when they will fix it. 

I tried to do an override for that method, but its private. Overriding the whole class is not working for me for some reason.

**Comment by gmalhotra02** [comment]
> > > > I am facing the same error in Magento 2.4.3 any solution?
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > error is : Type Error occurred when creating object: Magento\InventorySourceSelection\Model\Address, Argument 1 passed to Magento\InventorySourceSelection\Model\Address::__construct() must be of the type string, null given, called in /var/www/public_html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121
> > > 
> > > 
> > > Are you using Amasty Shipping Table rates?
> > 
> > 
> > Yes, I am using Amasty Shipping Table rate extension. Any changes to be done to the module ?
> 
> Go to: /Model/Quote/Inventory/InventoryRequestFromQuoteFactory.php
> 
> and change:
> 
> ```
> -            'country'   => $shippingAddress->getCountryId(),
> +            'country'   => $shippingAddress->getCountryId() ?? '',
> ```
> 
> This fixed the issue for me.
> 
> To test you can:
> 
> Use guest account, add to cart, then go straight to login page and log in. This should show the error on cart / checkout pages.
> 
> I requested Amasty team expedite this fix, but I don't know when they will fix it.
> 
> I tried to do an override for that method, but its private. Overriding the whole class is not working for me for some reason.

Thank you and this worked for me as well. No more errors now, will wait for Amasty team to update

**Comment by pmonosolo** [comment]
> > > > > I am facing the same error in Magento 2.4.3 any solution?
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > error is : Type Error occurred when creating object: Magento\InventorySourceSelection\Model\Address, Argument 1 passed to Magento\InventorySourceSelection\Model\Address::__construct() must be of the type string, null given, called in /var/www/public_html/magento2/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 121
> > > > 
> > > > 
> > > > Are you using Amasty Shipping Table rates?
> > > 
> > > 
> > > Yes, I am using Amasty Shipping Table rate extension. Any changes to be done to the module ?
> > 
> > 
> > Go to: /Model/Quote/Inventory/InventoryRequestFromQuoteFactory.php
> > and change:
> > ```
> > -            'country'   => $shippingAddress->getCountryId(),
> > +            'country'   => $shippingAddress->getCountryId() ?? '',
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This fixed the issue for me.
> > To test you can:
> > Use guest account, add to cart, then go straight to login page and log in. This should show the error on cart / checkout pages.
> > I requested Amasty team expedite this fix, but I don't know when they will fix it.
> > I tried to do an override for that method, but its private. Overriding the whole class is not working for me for some reason.
> 
> Thank you and this worked for me as well. No more errors now, will wait for Amasty team to update

The official fix from Amasty team coming out next month.

**Comment by fm-cl** [comment]
Hello @pmonosolo 

I had this same issue, and this fixed for me. Thank you alot you made my day!

**Comment by pmonosolo** [comment]
> Hello @pmonosolo
> 
> I had this same issue, and this fixed for me. Thank you alot you made my day!

The issue has been solved in latest release of the plugin (1.10.3). Have not tested yet, but that's what I've been told.
